---

default:
  tags:
    - build-runner

# variables:
#   # Disable TLS cert generation (optional, depending on your setup)
#   DOCKER_TLS_CERTDIR: ""

stages:
  - build

build:
  image: 579238664596.dkr.ecr.ap-southeast-2.amazonaws.com/kaniko:latest
  stage: build
  script:
    # Build the Docker image using Kaniko, reading the context and Dockerfile from your project.
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
